#!/bin/sh

set -e

root_dir=$(git rev-parse --show-toplevel)

. "$root_dir/.githooks/venv.sh"
set_venv_python "$root_dir"

dotnet restore "$root_dir"
"$VENV_PY" -m pip install -r "$root_dir/requirements.txt"
